name: "Magento compilation (setup:di:compile)"
author: "Graycore"
description: "A Github Action that runs bin/magento setup:di:compile."

inputs:
  php_version:
    required: true
    default: "8.1"
    description: "PHP version used to do the coding standard check."

  composer_version:
    required: true
    default: "2"
    description: "The version of composer to use."

runs:
  using: composite
  steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}
        coverage: none

    - name: Install composer dependencies
      shell: bash
      run: composer install

    - name: Enable all modules
      shell: bash
      run: php bin/magento module:enable --all

    - name: Compile
      shell: bash
      run: php bin/magento setup:di:compile
